#!/bin/bash
GPU=$(lspci | grep -E "VGA|3D" | grep -oE "Intel|NVIDIA|AMD" | head -1)
case $GPU in
    Intel) sudo pacman -S --noconfirm xf86-video-intel ;;
    NVIDIA) sudo pacman -S --noconfirm nvidia nvidia-utils ;;
    AMD) sudo pacman -S --noconfirm xf86-video-amdgpu ;;
    *) sudo pacman -S --noconfirm xf86-video-vesa ;;
esac
echo "Controladores instalados"
