#!/bin/bash
REPO_BASE="https://github.com/XONIDU"
cd "$HOME"
echo "Herramientas: xonitube, xonigraf, xonichat, xonimail"
read -p "Nombre: " TOOL
if [ -n "$TOOL" ]; then
    [ -d "$TOOL" ] || git clone "$REPO_BASE/$TOOL.git"
    if [ -f "$TOOL/start.py" ]; then
        sudo ln -sf "$HOME/$TOOL/start.py" "/usr/local/bin/$TOOL"
        echo "$TOOL instalado"
    fi
fi
