#!/bin/bash
REPO="https://github.com/XONIDU/xoniarch.git"
DIR="/opt/xoniarch"
if [ ! -d "$DIR" ]; then
    sudo git clone "$REPO" "$DIR"
else
    cd "$DIR" && sudo git pull
fi
sudo cp "$DIR"/scripts/xoniarch-* /usr/local/bin/
sudo chmod +x /usr/local/bin/xoniarch-*
echo "XONIARCH actualizado"
